<?php

/**
 * @file
 * Defines all the hooks this module implements.
 *
 * islandora_jobs_monitor.module: defines paths as entry points and acts
 *  as a hub for dispatching tasks to other modules.
 *
 * This file is a utility module for use with Islandora.
 *
 * WARNING: Part of this module does not adhere to standard drupal database
 * settings.  This can be installed as either a master or a worker or even as
 * a drupal-free-worker in the case of the cron_fedora_health.php script.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the program.  If not, see <http ://www.gnu.org/licenses/>.
 */

// Permissions.
define('ISLANDORA_USE_STACK_MONITOR', 'use islandora jobs monitor');

/**
 * Implements hook_menu().
 */
function islandora_jobs_monitor_menu() {
  $menu = array(
    'admin/islandora/islandora_job_monitor' => array(
      'title' => 'Islandora Jobs Monitor',
      'description' => 'Change the settings for Islandora Jobs Monitor.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_jobs_monitor_admin_form'),
      'access arguments' => array(ISLANDORA_MANAGE_PROPERTIES),
      'file' => 'includes/admin.form.inc',
    ),
    'islandora/islandora_job_monitor' => array(
      'title' => 'Islandora Jobs Monitor',
      'description' => 'To gather and report health and job processing for relevant jobs servers.',
      'page callback' => array('islandora_jobs_monitor_page'),
      'file' => 'includes/islandora_jobs_monitor.page.inc',
      'access arguments' => array(ISLANDORA_USE_STACK_MONITOR),
    ),
    'islandora/islandora_job_monitor/api/serverhealth' => array(
      'title' => 'Islandora Jobs Monitor API endpoint for server health',
      'file' => 'includes/api.inc',
      'page callback' => array('islandora_jobs_monitor_api_serverhealth'),
    )
  );
  
  return $menu;
}

/**
 * Implements hook_presprocess_theme().
 *
 * This code will remove the sidebar and will add the stylesheet and js needed
 * for the report display.
 */
function islandora_jobs_monitor_preprocess_page(&$vars) {
  $item = menu_get_item();
  if (is_array($item)) {
    if ($item['path'] == 'islandora/islandora_job_monitor') {
      $module_path = drupal_get_path('module', 'islandora_jobs_monitor');
      drupal_add_css($module_path . '/css/islandora_jobs_monitor.css');
      drupal_add_js($module_path . '/js/islandora_jobs_monitor.js');
      $vars['sidebar'] = array();
    }
  }
}

/**
 * Implements hook_theme().
 */
function islandora_jobs_monitor_theme() {
  return array(
    'islandora_jobs_monitor_page' => array(
      'template' => 'theme/islandora-jobs-monitor-page',
      'variables' => array(
        'themed_hosts' => '',
        'current_report' => '',
      ),
    ),
    'islandora_jobs_monitor_themed_worker' => array(
      'template' => 'theme/islandora-jobs-monitor-themed-worker',
      'variables' => array(
        'host_record' => '',
      ),
    ),
    'islandora_jobs_monitor_themed_master' => array(
      'template' => 'theme/islandora-jobs-monitor-themed-master',
      'variables' => array(
        'host_record' => '',
      ),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function islandora_jobs_monitor_permission() {
  return array(
    ISLANDORA_USE_STACK_MONITOR => array(
      'title' => t('Use the Islandora Jobs Stack Monitor'),
      'description' => t('User can use the Islandora Jobs Stack Monitor.'),
    ),
  );
}

/**
 * Helper function to connect to the bigfoot database using the site's settings.php file.
 */
function islandora_jobs_monitor_get_databaselink($db_section = 'default') {
  global $databases;
  // Use the settings.php file for this install.
  $settings_file = variable_get('islandora_jobs_monitor_settings_file', '/var/www/html/drupal_gamera_sandbox/sites/gamera.library.pitt.edu/settings.php');
  if (!$settings_file) {
    drupal_set_message('The settings file value has not been set.  It is needed in order ' .
      'to be able to run the drush commands with the appropriate include path. ' .
      l('Configure Islandora Jobs Monitor here', 'admin/islandora/islandora_jobs_monitor') . '.');
    return NULL;
  }
  require_once($settings_file);

  if (count($databases) < 1 || !array_key_exists($db_section, $databases['default'])) {
    die('Database settings not found at ' . $settings_file . '.');
  }

  $db_host = $databases['default'][$db_section]['host'];
  $db_user = $databases['default'][$db_section]['username'];
  $db_pass = $databases['default'][$db_section]['password'];
  $db_name = $databases['default'][$db_section]['database'];

  $link = mysqli_connect($db_host, $db_user, $db_pass, $db_name);
  if (mysqli_connect_errno()) {
    printf("Connect failed: %s\n", mysqli_connect_error());
    exit();
  }

  return $link;
}

function islandora_jobs_monitor_sql_error_die($link, $sql) {
  $message  = 'Invalid query: ' . mysqli_error($link) . "<br>";
  $message .= 'Query: <pre>' . $sql ."</pre>";
  $bt = debug_backtrace();
  $variables = array('@sql' => $sql, '@backtrace' => $bt);
  watchdog('islandora_jobs_monitor', 'There was an error executing a database query.  The sql = @sql.  Debug backtrace @backtrace', $variables, WATCHDOG_ERROR);
  die($message);
}

/**
 * Implements islandora_job_submitted().
 * 
 * This will take the payload and create a record that matches the current 
 * hostname particular to the worker that has picked up the job.
 */
function islandora_jobs_monitor_islandora_job_started($payload) {
  module_load_include('inc', 'islandora_jobs_monitor', 'includes/db');
  // Use the $jobname and the ip_address to create a record in the
  // `host_gearman_job` table that matches the server that has this ip_address.
  $server_id = islandora_jobs_monitor_get_server_id_of_ip($_SERVER['SERVER_ADDR']);
  if ($server_id) {
    $payload_as_arr = json_decode($payload, true);
    $jobname = $payload_as_arr['func'];
    $args = $payload_as_arr['args'];
    if (count($args) > 0) {
      $pid = $args[0];
    }

    islandora_jobs_monitor_add_job_record($server_id, $pid, $jobname);
  }
  else {
    $variables = array('@ip_address' => $_SERVER['SERVER_ADDR']);
    watchdog('islandora_jobs_monitor', 'There was no record in `islandora_jobs_monitor`.`servers` for ip_address = "@ip_address."', $variables, WATCHDOG_ERROR);
  }
}